server:
  servlet:
    session:
      timeout: 15d
      cookie:
        secure: true
        name: LIVEMINDS_COOKIE
        http-only: true

spring:
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone=UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
  
hibernate:
  jdbc:
    time_zone=UTC

logging:
  level:
    root: INFO
    io.github.ismaele77.liveminds: DEBUG
  file:
    name: application.log
    max-history: 1
    max-size: 10MB
    clean-history-on-start: true
