server:
  servlet:
    session:
      timeout: 10800
      cookie:
        max-age: 1800
        secure: true
        http-only: true

spring:
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true


