server:
  servlet:
    session:
      timeout: 10800
      cookie:
        max-age: 1800
        secure: true
        http-only: true

spring:
  config:
    import: optional:secrets.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

#Set root logging level
logging:
  level:
    root: INFO
    io.github.ismaele77.liveminds: DEBUG
  file:
    name: application.log
    max-history: 1
    max-size: 10MB
    clean-history-on-start: true
