livekit:
  host: http://localhost:7880
  apiKey: devkey
  secret: secret
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liveminds
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver